// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bento: dynamic(() => import("./Bento")),
  case_studies: dynamic(() => import("./CaseStudies")),
  hero: dynamic(() => import("./Hero")),
  integrations: dynamic(() => import("./Integrations")),
  personalised_text: dynamic(() => import("./PersonalisedText")),
  showcase: dynamic(() => import("./Showcase")),
};
